# Generated by Django 4.2.7 on 2023-11-19 15:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_api_v1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="app_api_v1.author"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "books",
            },
        ),
    ]
