# Generated by Django 4.2.7 on 2023-12-23 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_api_v3", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title", "pk"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
