# Generated by Django 4.2.7 on 2023-12-23 23:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api_v3", "0002_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.TextField(unique=True),
        ),
    ]
