# Generated by Django 4.2.7 on 2023-12-23 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_api_v1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["name", "pk"],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
    ]
